

- name: Copy the node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Get lustre exporter state
  command: "ps --format pid,cmd --no-headers -C lustre_exporter"
  register: lustre_exporter_ps
  failed_when: false
  changed_when: false

- name: Start lustre exporter
  # Note that just rerunning the command if its already running fails with  `bind: address already in use`.
  # Shows skip rather than OK if command was already running. TODO: fix running with wrong parameters?
  shell: "nohup {{ lustre_exporter_src }}/lustre_exporter {{ lustre_exporter_collectors | join(' ') }} </dev/null >/dev/null 2>&1 &"
  when: "lustre_exporter_ps.stdout == '' and lustre_exporter_state == 'started'"
  
- name: Stop lustre exporter
  shell:
    cmd: "kill {{ lustre_exporter_ps.stdout.split()[0] }}" # split gets pid
  when: "lustre_exporter_ps.stdout != '' and lustre_exporter_state == 'stopped'"
  
# TODO: handled changed flags!
# TODO: add enabled / start-on-boot options


  
# wget https://golang.org/dl/go1.12.17.linux-amd64.tar.gz
# sudo tar -C /usr/local -xzf go1.12.17.linux-amd64.tar.gz
# export PATH=$PATH:/usr/local/go/bin
# git clone github.com/marquis-wang/lustre_exporter
# cd go/src/github.com/marquis-wang/lustre_exporter/
# make build # avoids failing lint steps




# wget https://golang.org/dl/go1.12.17.linux-amd64.tar.gz



# sudo tar -C /usr/local -xzf go1.15.6.linux-amd64.tar.gz


# wget https://golang.org/dl/go1.11.13.linux-amd64.tar.gz
#   yum:
#     name: go
#   become: true
# - name: Get lustre-exporter
#   command:
#     cmd: "go get {{ lustre_exporter_repo }}"
# - name: Build lustre-exporter
#   command:
#     cmd: "make"
#     chdir: "{{ ansible_env.HOME }}/go/src/github.com/HewlettPackard/lustre_exporter"
#     #creates: 
