- name: check Centos version
  assert:
    that:
      - ansible_distribution_version in lustre_releases
- name: select lustre version info # just for brevity 
  set_fact:
    lustre_release: "{{ lustre_releases[ansible_distribution_version] }}"
- name: install kernel
  yum:
    name: https://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/kernel-{{ lustre_release.kernel_ver }}.{{ ansible_architecture }}.rpm
- name: check kernel version
  shell:
    cmd: "uname -r"
  register: uname
  changed_when: false
- name: reboot if kernel updated
  reboot:
  when: lustre_release.kernel_ver not in uname.stdout
- name: enable lustre server repo
  yum_repository:
    name: lustre-server
    description: lustre-server
    file: lustre-repo
    baseurl: https://downloads.whamcloud.com/public/lustre/lustre-{{ lustre_release.lustre_ver }}/el{{ ansible_distribution_major_version }}/patchless-ldiskfs-server
    gpgcheck: no
- name: enable lustre e2fs repo
  yum_repository:
    name: e2fsprogs-wc
    description: e2fsprogs-wc
    file: lustre-repo
    baseurl: https://downloads.whamcloud.com/public/e2fsprogs/1.45.2.wc1/el7/
    gpgcheck: no
- name: Install Lustre Server
  yum:
    name: "lustre-{{ lustre_release.lustre_ver }}"
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
# - name: configure and enable lnet
#   import_tasks: lnet.yml
- name: format and mount MDT/OST/MGS disks
  import_tasks: format.yml
