- name: check kernel version
  shell:
    cmd: "uname -r"
  register: uname
  changed_when: false
- name: install kernel
  yum:
    name: https://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/kernel-{{ lustre_kernel }}.rpm
    state: present
  register: update_kernel
  when: uname.stdout != lustre_kernel
- name: reboot if kernel updated
  reboot:
  when: update_kernel is changed
- name: enable lustre server repo
  yum_repository:
    name: lustre-server
    description: lustre-server
    file: lustre-repo
    baseurl: https://downloads.whamcloud.com/public/lustre/lustre-{{ lustre_release }}/el7/patchless-ldiskfs-server
    gpgcheck: no
- name: enable lustre e2fs repo
  yum_repository:
    name: e2fsprogs-wc
    description: e2fsprogs-wc
    file: lustre-repo
    baseurl: https://downloads.whamcloud.com/public/e2fsprogs/1.45.2.wc1/el7/
    gpgcheck: no
- name: Install Lustre Server
  yum:
    name: "lustre-{{ lustre_release }}"
    state: present
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
# - name: configure and enable lnet
#   import_tasks: lnet.yml
- name: format and mount MDT/OST/MGS disks
  import_tasks: format.yml
