lustre_reformat: false # need this true if e.g. mdt was formatted with wrong index
lustre_fs_name: 'dac'
lustre_mgs_addr: ''
lustre_mgs_lnet: '' 
lustre_mgt: ''
lustre_mdts: []
lustre_osts: []
lustre_lnet: 'tcp'

# NB: release and kernel need to match centos version - this is set up for 7.8
# lustre_squash_gid: 99
# lustre_squash_uid: 99

# no default:
# lustre_fs_name: