# Need this fork for lustre 1.12 support github.com/marquis-wang/lustre_exporter
# However install instructions using `go get` don't work so have to do it manually instead

# - name: Install make # just assume this ... TODO: document assumes make
#   package:
#     name: make
- name: Make build dir
  file:
    path: "{{ lustre_exporter_builddir }}"
    state: directory
- name: Install go v 1.12
  unarchive:
    remote_src: yes
    src: https://golang.org/dl/go1.12.17.linux-amd64.tar.gz
    dest: "{{ lustre_exporter_builddir }}"
- name: Clone fork of HP lustre exporter supporting lustre 1.12 # using `go get` doesn't work
  git:
    repo: "https://github.com/marquis-wang/lustre_exporter"
    dest: "{{ lustre_exporter_builddir}}/{{lustre_exporter_src }}" # makes it match what makefile expects if fork was merged
    version: c362e91
- name: Build # TODO: document needs facts=true
  command:
    cmd: "make build" # uses build to avoid failing lint steps
    #cmd: "echo {{ ansible_env.PATH }}:{{ lustre_exporter_builddir}}/go/bin"
    # cmd: "echo $PATH"
    chdir: "{{ lustre_exporter_builddir}}/{{lustre_exporter_src }}"
    creates: "{{ lustre_exporter_builddir}}/{{lustre_exporter_src }}/lustre_exporter"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lustre_exporter_builddir}}/go/bin"
