---

- name: Configure lustre servers
  hosts: servers
  gather_facts: true
  become: true
  tags: servers
  tasks:
    # - include_role:
    #     name: stackhpc.ofed
    #   vars:
    #     ofed_repo_file: http://linux.mellanox.com/public/repo/mlnx_ofed/5.1-2.3.7.1/rhel8.2/mellanox_mlnx_ofed.repo
    # - meta: end_play
    - name: Create loop device for MGT
      include_role:
        name: loopdev
      vars:
        loopdev_path: "/var/mgt"
        loopdev_size: 20000
      register: loopdev
      when: "'mgs' in group_names"
    - debug:
        msg: "Got loop device {{ loopdev.dev }} ({{ loopdev.fstype }}) for backing file {{ loopdev.path }} "
      when: "'mgs' in group_names"
    - name: Configure lustre servers
      include_role:
        name: server
      vars:
        lustre_mgs_addr: "{{ hostvars[groups['mgs'] | first].ansible_p8p2.ipv4.address }}"
    - name: Install lustre exporter
      include_role:
        name: lustre-exporter
        tasks_from: install
