# NB: We want this fork for lustre 1.12 support github.com/marquis-wang/lustre_exporter
# Official install instructions don't work so do it manually instead

# --collector.ost=disabled --collector.mdt=core --collector.mgs=extended


# msg: "--collector.{{ item.key }}={{ item.value}}"
#loop: "{{ lustre_exporter_flags | dict2items }}"
#  lustre_exporter_flags | dict2items | map(attribute='key') | list }}"

- name: Install make
  yum:
    name: make
  become: true
- name: Install go v 1.12
  unarchive:
    remote_src: yes
    src: https://golang.org/dl/go1.12.17.linux-amd64.tar.gz
    dest: /usr/local
  become: true
- name: Clone fork of HP lustre exporter supporting lustre 1.12 # using `go get` doesn't work
  git:
    repo: "https://github.com/marquis-wang/lustre_exporter"
    dest: "{{ lustre_exporter_src }}" # makes it match what makefile expects if fork was merged
    version: c362e91
- name: Build
  command:
    cmd: "make build" # uses build to avoid failing lint steps
    chdir: "{{ lustre_exporter_src }}"
    creates: "{{ lustre_exporter_src }}/lustre_exporter"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

- set_fact:
    lustre_exporter_collectors: "{{ lustre_exporter_collectors | default([]) + [ '--collector.' + item.key + '=' + item.value ] }}"
  loop: "{{ lustre_exporter_flags |  dict2items}}"

- name: Get lustre exporter state
  command: "ps --format pid,cmd --no-headers -C lustre_exporter"
  register: lustre_exporter_ps
  failed_when: false
  changed_when: false

- name: Start lustre exporter
  # Note that just rerunning the command if its already running fails with  `bind: address already in use`.
  # Shows skip rather than OK if command was already running. TODO: fix running with wrong parameters?
  shell: "nohup {{ lustre_exporter_src }}/lustre_exporter {{ lustre_exporter_collectors | join(' ') }} </dev/null >/dev/null 2>&1 &"
  when: "lustre_exporter_ps.stdout == '' and lustre_exporter_state == 'started'"
  
- name: Stop lustre exporter
  shell:
    cmd: "kill {{ lustre_exporter_ps.stdout.split()[0] }}" # split gets pid
  when: "lustre_exporter_ps.stdout != '' and lustre_exporter_state == 'stopped'"
  
# TODO: handled changed flags!
# TODO: add enabled / start-on-boot options


  
# wget https://golang.org/dl/go1.12.17.linux-amd64.tar.gz
# sudo tar -C /usr/local -xzf go1.12.17.linux-amd64.tar.gz
# export PATH=$PATH:/usr/local/go/bin
# git clone github.com/marquis-wang/lustre_exporter
# cd go/src/github.com/marquis-wang/lustre_exporter/
# make build # avoids failing lint steps




# wget https://golang.org/dl/go1.12.17.linux-amd64.tar.gz



# sudo tar -C /usr/local -xzf go1.15.6.linux-amd64.tar.gz


# wget https://golang.org/dl/go1.11.13.linux-amd64.tar.gz
#   yum:
#     name: go
#   become: true
# - name: Get lustre-exporter
#   command:
#     cmd: "go get {{ lustre_exporter_repo }}"
# - name: Build lustre-exporter
#   command:
#     cmd: "make"
#     chdir: "{{ ansible_env.HOME }}/go/src/github.com/HewlettPackard/lustre_exporter"
#     #creates: 
